artifacts:
  jruby: "org.jruby:jruby-complete:jar:1.1.3"
  servlet: "javax.servlet:servlet-api:jar:2.4"
  jsp_api: "javax.servlet:jsp-api:jar:2.0"
  bsf: "bsf:bsf:jar:2.4.0"
  jcl: "commons-logging:commons-logging:jar:1.0.4"
  jcio: "commons-io:commons-io:jar:1.4"
  jclang: "commons-lang:commons-lang:jar:2.3"
  freemarker: "org.freemarker:freemarker:jar:2.3.13"
  string_taglib: "taglibs:string:jar:1.1.0"
  spring_mock: "org.springframework:spring-mock:jar:2.0.7"
  spring: "org.springframework:spring:jar:2.0.7"